In [2]:
import numpy as np

### 연습문제 2.2.4

#### (1)

In [3]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2], [3, 4], [5, 6]])

In [4]:
AB = A@B
print(AB)

[[22 28]
 [49 64]]


#### (2)

In [5]:
BA = B@A
print(BA)

[[ 9 12 15]
 [19 26 33]
 [29 40 51]]


#### (3)

In [6]:
A = np.array([1, 2, 3])
B = np.array([[4, 5, 6], [7, 8, 9]])

In [7]:
AB = np.dot(A, B)

ValueError: shapes (3,) and (2,3) not aligned: 3 (dim 0) != 2 (dim 0)

In [11]:
BA = np.dot(B, A)
print(BA)

[32 50]


#### (4)

In [12]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [13]:
AB = np.dot(A, B)
print(AB)
BA = np.dot(B, A)
print(BA)

[[19 22]
 [43 50]]
[[23 34]
 [31 46]]


#### (5)

In [15]:
A = np.array([[1, 2], [3, 4], [5, 6]])
print(A)
print(A.T)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [16]:
AAT = A@A.T
print(AAT)

[[ 5 11 17]
 [11 25 39]
 [17 39 61]]


In [17]:
ATA = A.T@A
print(ATA)

[[35 44]
 [44 56]]


#### (6)

In [18]:
x = np.array([[1], [2], [3]])
print(x)
print(x.T)

[[1]
 [2]
 [3]]
[[1 2 3]]


In [19]:
XTX = x.T@x
print(XTX)

[[14]]


In [20]:
XXT = x@x.T
print(XXT)

[[1 2 3]
 [2 4 6]
 [3 6 9]]


### 연습문제 2.5.5

#### (1)

In [104]:
x = np.array([[1], [2], [3]])
N = x.shape[0]
one_N = np.ones((N, 1))

print(x)
print(one_N)

[[1]
 [2]
 [3]]
[[1.]
 [1.]
 [1.]]


In [105]:
print(x.T)
res =  one_N @ x.T
print(res)

[[1 2 3]]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [103]:
repeated_x = np.array([x.T, x.T, x.T])
print(repeated_x)

[[[1 2 3]]

 [[1 2 3]]

 [[1 2 3]]]


#### (2)

In [95]:
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(X)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [112]:
# 각 열의 평균으로 이루어진 벡터 구하기
N = X.shape[0] # 행 개수
M = X.shape[1] # 열 개수
arr = []

for i in range(M) :
    x_bar = np.sum(X.T[i]) / N
    arr.append(x_bar)

x_bar = np.array([arr])
print(x_bar)

[[5.5 6.5 7.5]]


In [114]:
print(1/N * (X.T @ np.ones(N)))

[5.5 6.5 7.5]


#### (3)

In [134]:
X_bar = np.tile(x_bar, (N, 1))
print(X_bar)

[[5.5 6.5 7.5]
 [5.5 6.5 7.5]
 [5.5 6.5 7.5]
 [5.5 6.5 7.5]]


In [130]:
print(1/N * np.dot(np.ones((N, 1)), np.ones((N, 1)).T) @ X)

[[5.5 6.5 7.5]
 [5.5 6.5 7.5]
 [5.5 6.5 7.5]
 [5.5 6.5 7.5]]


#### (4)

In [136]:
from sklearn.datasets import load_iris
X = load_iris().data

In [138]:
print(X)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [139]:
N = X.shape[0] # 행 개수

print(1/N * np.dot(np.ones((N, 1)), np.ones((N, 1)).T) @ X)

[[5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 

### 연습문제 2.2.6

In [9]:
first = np.array([[1, 2]]) @ np.array([[1, 2], [3, 4]]) @ np.array([[5], [6]])
second = np.array([[1, 2]]) @ (np.array([[1, 2], [3, 4]]) @ np.array([[5], [6]]))

print(first)
print(second)

[[95]]
[[95]]


### 연습문제 2.2.7

In [20]:
X = np.array([[1, 2, 3], [4, 5, 6]])
print(X)

[[1 2 3]
 [4 5 6]]


In [21]:
w = np.array([2, 3, 4])
print(w)

[2 3 4]


In [22]:
# c1, c2, c3는 X의 열 벡터
c1 = X[:, 0]
c2 = X[:, 1]
c3 = X[:, 2]

print(c1)

[1 4]


In [24]:
Xw = X @ w
print(Xw)

[20 47]


In [25]:
linear = w[0]*c1 + w[1]*c2 + w[2]*c3
print(linear)

[20 47]


### 연습문제 2.2.8

In [26]:
# v1, v2, v3 벡터 정의
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
v3 = np.array([7, 8, 9])

# V 행렬 정의
V = np.column_stack((v1, v2, v3))
print(V)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [27]:
# λ 벡터 정의
lambda_vec = np.array([2, 0, 0]) # λ1 = 2

# Vλ 계산
V_lambda = V @ lambda_vec
print(V_lambda)

[2 4 6]


In [28]:
# λ1 * v1 계산
lambda_v1 = lambda_vec[0] * v1
print(lambda_v1)

[2 4 6]


In [29]:
np.allclose(V_lambda, lambda_v1)

True

### 연습문제 2.2.9

In [42]:
# x1, x2 정의 (임의의 값으로 설정)
x1 = np.array([[1], [2], [3]])
x2 = np.array([[4], [5], [6]])

# X 정의 (x1, x2가 행 벡터로 쌓인 행렬)
X = np.vstack((x1.T, x2.T))
print(X)

[[1 2 3]
 [4 5 6]]


In [43]:
w = np.array([[7], [8], [9]])

Xw = X @ w
print(Xw)

[[ 50]
 [122]]


In [50]:
x1Tw = x1.T @ w
x2Tw = x2.T @ w
combine = np.vstack((x1Tw, x2Tw))
print(combine)

[[ 50]
 [122]]


In [51]:
print(np.allclose(Xw, combine))

True


### 연습문제 2.2.11

In [52]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [53]:
A = np.arange(1, 10).reshape(3, 3)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
x.T @ A @ x

np.int64(228)

### 연습문제 2.2.12

In [55]:
x = np.array([2, 4, 6])
A = np.arange(1, 10).reshape(3, 3)

x.T @ A @ x

np.int64(912)

In [56]:
1/2 * (x.T @ (A + A.T) @ x)

np.float64(912.0)

### 연습문제 2.2.13

In [57]:
# v1, v2, v3 벡터 정의
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
v3 = np.array([7, 8, 9])

# V 행렬 정의
V = np.column_stack((v1, v2, v3))

print(V)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [58]:
# A 정방행렬 정의 (임의의 값으로 설정)
A = np.array([[1, 0, 2],
              [0, 1, 1],
              [1, 2, 1]])

# Λ 대각행렬 정의
Lambda = np.diag([2, 3, 4])
print(Lambda)

[[2 0 0]
 [0 3 0]
 [0 0 4]]


In [61]:
# AV 계산
AV = A @ V
print(AV)

sumAV = np.column_stack((A @ v1, A @ v2, A @ v3)) 
print(sumAV)

np.allclose(AV, sumAV)

[[ 7 16 25]
 [ 5 11 17]
 [ 8 20 32]]
[[ 7 16 25]
 [ 5 11 17]
 [ 8 20 32]]


True

In [63]:
# VΛ 계산
V_Lambda = V @ Lambda
print(V_Lambda)

sumV_Lambda =np.column_stack((2*v1, 3*v2, 4*v3))
print(sumV_Lambda)

np.allclose(V_Lambda, sumV_Lambda)

[[ 2 12 28]
 [ 4 15 32]
 [ 6 18 36]]
[[ 2 12 28]
 [ 4 15 32]
 [ 6 18 36]]


True

### 연습문제 2.2.14

In [65]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
a3 = np.array([7, 8, 9])

A = np.vstack((a1, a2, a3))
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [70]:
ATA = A.T @ A
print(A.T)
print(ATA)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[ 66  78  90]
 [ 78  93 108]
 [ 90 108 126]]


In [73]:
a1T = a1.reshape(3, 1)
a2T = a2.reshape(3, 1)
a3T = a3.reshape(3, 1)

AT = np.hstack((a1T, a2T, a3T))
print(AT)
AT_A = AT @ A
print(AT_A)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[ 66  78  90]
 [ 78  93 108]
 [ 90 108 126]]
