In [2]:
import numpy as np

### 연습문제 2.3.2

In [3]:
# 임의의 행렬 A 정의
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [6]:
# ||A||^2 계산: 행렬 A의 모든 요소 제곱의 합
norm_A_squared = np.sum(A**2)

# 위에서 아래로 열방향 계산, 행 벡터의 제곱합 총합
norm_row_squared = np.sum(np.sum(A**2, axis=1))

# 왼쪽에서 오른쪽으로 행 방향 계산, 열 벡터의 제곱합 총합
norm_col_squared = np.sum(np.sum(A**2, axis=0))

print(norm_A_squared)
print(np.allclose(norm_A_squared, norm_row_squared) and np.allclose(norm_A_squared, norm_col_squared))

285
True


### 연습문제 2.3.3

In [14]:
x = np.array([[1], [2]])
A = np.array([[3, 4], [5, 6]])

# 이차형식의 대각합
xTAx = x.T @ A @ x
print(xTAx)

tr_xTAx = np.trace(np.array([[xTAx]]))
print(tr_xTAx)

xxTA = x @ x.T @ A
print(xxTA)

tr_xxTA = np.trace(np.array([[xxTA]]))
print(tr_xxTA)

AxxT = A @ x @ x.T 
print(AxxT)

tr_AxxT = np.trace(np.array([[AxxT]]))
print(tr_AxxT)

[[45]]
[[45]]
[[13 16]
 [26 32]]
[[13 16]
 [26 32]]
[[11 22]
 [17 34]]
[[11 22]
 [17 34]]


### 연습문제 2.3.5

In [16]:
A = np.array([[1, 2], [3, 4]])
norm_A_squared = np.sum(A**2)
print(norm_A_squared)

ATA = A.T @ A
print(ATA)

tr_ATA = np.trace(ATA)
print(tr_ATA)

30
[[10 14]
 [14 20]]
30


### 연습문제 2.3.6

In [20]:
A = np.array([[5, 6], [8, 9]])
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

j_0 = 1
det_A = ((-1)**(1+1))*9*5 + ((-1)**(2+1))*6*8
print(det_A)
det_AA = 5*9 - 6*8
print(det_AA)

det_M1 = det_A
det_M2 = ((-1)**(1+1))*9*2 + ((-1)**(2+1))*3*8
det_M3 = ((-1)**(1+1))*6*2 + ((-1)**(2+1))*3*5

det_B = ((-1)**(1+1))*det_M1*1 + ((-1)**(2+1))*det_M2*4 + ((-1)**(3+1))*det_M3*7
print(det_B)
det_BB = 1*5*9 - 1*6*8 - 2*4*9 + 3*4*8 + 2*6*7 - 3*5*7 
print(det_BB)


-3
-3
0
0


### 연습문제 2.3.7

In [25]:
A = np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 2]])
B = np.array([[1, 2], [3, 4]])

C = np.array([[1], [2], [3]])
D = np.array([[1], [2]])
print(C.T @ A @ C)
print(D.T @ B @ D)

tr_A = np.trace(A)
tr_B = np.trace(B)
print(tr_A)
print(tr_B)

det_A = ((-1)**(1+1))*2*(2*2 - (-1)*(-1)) + ((-1)**(2+1))*(-1)*((-1)*2 - 0*(-1)) + ((-1)**(3+1))*(0)*((-1)*(-1) - 0*2)
det_B = 1*(4) - 2*3
print(det_A)
print(det_B)

print(np.linalg.det(A))
print(np.linalg.det(B))

[[12]]
[[27]]
6
5
4
-2
4.0
-2.0000000000000004
