In [3]:
import numpy as np

### 연습문제 2.4.3

#### (1)

In [4]:
A = np.array([[2, 0], [0, 1]])
det_A = np.linalg.det(A)
invert_A = 1/det_A * np.array([[1, 0], [0, 2]]).T
print(invert_A)
print(np.linalg.inv(A))

[[0.5 0. ]
 [0.  1. ]]
[[0.5 0. ]
 [0.  1. ]]


#### (2)

In [5]:
A = np.array([[1 / np.sqrt(2), -1 / np.sqrt(2)], [1 / np.sqrt(2), 1 / np.sqrt(2)]])
det_A = np.linalg.det(A)
invert_A = 1/det_A * np.array([[1 / np.sqrt(2), -1 / np.sqrt(2)], [1 / np.sqrt(2), 1 / np.sqrt(2)]]).T
print(invert_A)
print(np.linalg.inv(A))

[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]


#### (3)

In [6]:
A = np.array([[3/np.sqrt(13), -1/np.sqrt(2)], [2/np.sqrt(13), 1/np.sqrt(2)]])
det_A = np.linalg.det(A)
invert_A = 1/det_A * np.array([[1/np.sqrt(2), -2/np.sqrt(13)],[1/np.sqrt(2), 3/np.sqrt(13)]]).T
print(invert_A)
print(np.linalg.inv(A))

[[ 0.72111026  0.72111026]
 [-0.56568542  0.84852814]]
[[ 0.72111026  0.72111026]
 [-0.56568542  0.84852814]]


#### (4)

In [7]:
A = np.array([[1, 1, 0], [0, 1, 1], [1, 1, 1]])

# 행렬식 계산
det_A = np.linalg.det(A)

# 코팩터 행렬 계산
# np.zeros_like는 입력된 배열과 동일한 모양(shape)과 데이터 타입을 가지며, 모든 원소가 0으로 초기화된 배열을 생성
cofactor_matrix = np.zeros_like(A, dtype=float)

for i in range(3):  # 행 인덱스
    for j in range(3):  # 열 인덱스
        # 소행렬 추출
        # np.ix_는 다차원 배열의 특정 행과 열을 교차하여 선택할 때 사용.
        # 전달된 각 리스트를 다차원 배열의 특정 축에 매핑하여, 
        # 선택된 인덱스의 **카티션 곱(Cartesian product)**을 반환합니다. 
        # 반환된 값은 항상 2차원 배열입니다.
        minor = A[np.ix_([x for x in range(3) if x != i], [y for y in range(3) if y != j])]
        # 코팩터 계산: 부호 처리 포함
        cofactor_matrix[i, j] = ((-1) ** (i + j)) * np.linalg.det(minor)

# 역행렬 계산
invert_A = (1 / det_A) * cofactor_matrix.T

print(invert_A)
print(np.linalg.inv(A))

[[ 0. -1.  1.]
 [ 1.  1. -1.]
 [-1. -0.  1.]]
[[ 0. -1.  1.]
 [ 1.  1. -1.]
 [-1.  0.  1.]]


### 연습문제 2.4.4

In [8]:
# 정방행렬 A와 B 정의
A = np.array([[2, 1],
              [3, 2]])

B = np.linalg.inv(A)  # A의 역행렬을 B로 정의

# 단위행렬 I 정의
I = np.eye(2)  # 2x2 단위행렬

AB = np.dot(A, B)
print(AB)
BA = np.dot(B, A)
print(BA)

print(np.allclose(AB, I))
print(np.allclose(BA, I))

[[1. 0.]
 [0. 1.]]
[[ 1.0000000e+00  0.0000000e+00]
 [-4.4408921e-16  1.0000000e+00]]
True
True


### 연습문제 2.4.5

In [9]:
import pandas as pd

data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

X = data
y = target

A = X[:4, [0, 4, 5, 6]]
b = y[:4]

In [11]:
print(A)

[[6.320e-03 5.380e-01 6.575e+00 6.520e+01]
 [2.731e-02 4.690e-01 6.421e+00 7.890e+01]
 [2.729e-02 4.690e-01 7.185e+00 6.110e+01]
 [3.237e-02 4.580e-01 6.998e+00 4.580e+01]]


In [12]:
print(b)

[24.  21.6 34.7 33.4]


In [14]:
x = np.dot(np.linalg.inv(A), b)
print(x)

[-3.12710043e+02 -1.15193942e+02  1.44996465e+01 -1.13259317e-01]


### 연습문제 2.4.6

In [15]:
Apinv = np.linalg.inv(A.T @ A) @ A.T
Apinv

array([[-2.35172493e+01,  4.95752613e+01, -9.28388535e+01,
         7.19277399e+01],
       [ 5.96138349e+00,  6.66097478e+00, -2.68388003e+01,
         1.58431788e+01],
       [-2.19803095e-01, -8.06127089e-01,  1.99308607e+00,
        -9.57270077e-01],
       [-9.40782133e-03,  2.15240112e-02,  2.94704793e-02,
        -4.11681401e-02]])

In [16]:
x = Apinv @ b
x

array([-3.12710043e+02, -1.15193942e+02,  1.44996465e+01, -1.13259317e-01])

In [17]:
A @ x

array([24. , 21.6, 34.7, 33.4])

In [18]:
b

array([24. , 21.6, 34.7, 33.4])