In [2]:
import numpy as np

### 연습문제 3.1.1

In [3]:
x1 = np.array([[1], [2]])
x2 = np.array([[2], [1]])

# A 행렬 구성
A = np.column_stack((x1, x2))

# A의 역행렬
A_inv = np.linalg.inv(A)

# 1번 방정식의 우변 b
b1 = np.array([[3], [1]])
c1c2_1 = A_inv @ b1
print(c1c2_1)

# 2번 방정식의 우변 b
b2 = np.array([[-1], [-1]])
c1c2_2 = A_inv @ b2
print(c1c2_2)

[[-0.33333333]
 [ 1.66666667]]
[[-0.33333333]
 [-0.33333333]]


### 연습문제 3.1.3

#### (1)

In [4]:
x = np.array([[1], [0]])

# 직교 조건을 만족하는 벡터의 일반적인 형식
# u = [u1, u2] satisfying x1 · u = 0
# Since x1 = [1, 0], the condition becomes: 1 * u1 + 0 * u2 = 0
# Therefore, u1 = 0, and u = [0, u2]

# u2를 1로 설정해 단순히 대표 벡터를 찾음
orthogonal_vector = np.array([0, 1])

#### (2)

In [5]:
from scipy.linalg import null_space

x = np.array([[1], [1]])

# 직교하는 벡터 계산 (일반적인 해: [-1, 1])
orthogonal_vector = np.array([-1, 1])

# 단위 벡터로 정규화
unit_vector = orthogonal_vector / np.linalg.norm(orthogonal_vector)

print("직교 벡터:", orthogonal_vector)
print("단위 직교 벡터:", unit_vector)

직교 벡터: [-1  1]
단위 직교 벡터: [-0.70710678  0.70710678]


#### (3)

In [6]:
# 주어진 벡터 x와 y
x = np.array([1, 1, 0])
y = np.array([1, 0, 0])

# 두 벡터에 직교하는 벡터를 찾기 위해 행렬 방정식 구성
A = np.vstack([x, y])  # x와 y를 쌓아 행렬 A를 만듦
b = np.array([0, 0])  # 결과는 0 벡터

# null space를 직접 계산: A · u = 0 만족하는 u를 찾음
# 자유 변수를 사용해 해를 계산
u = np.array([0, 0, 1])  # 직교하는 벡터 (z축 방향)

# 단위 벡터로 정규화
unit_vector = u / np.linalg.norm(u)

print("두 벡터에 직교하는 단위 벡터:", unit_vector)

두 벡터에 직교하는 단위 벡터: [0. 0. 1.]


### 연습문제 3.1.6

In [7]:
a = np.array([[4], [5], [2], [2]])
b = np.array([[4], [0], [2], [0]])
c = np.array([[2], [2], [0], [1]])

euclid_ab = np.linalg.norm(a - b) 
euclid_ac = np.linalg.norm(a - c)
euclid_bc = np.linalg.norm(b - c)

print(euclid_ab)
print(euclid_ac)
print(euclid_bc)

cosine_ab = 1 - (a.T @ b) / (np.linalg.norm(a) * np.linalg.norm(b))
cosine_ac = 1 - (a.T @ c) / (np.linalg.norm(a) * np.linalg.norm(c))
cosine_bc = 1 - (b.T @ c) / (np.linalg.norm(b) * np.linalg.norm(c))

print(cosine_ab)
print(cosine_ac)
print(cosine_bc)

5.385164807134504
4.242640687119285
3.605551275463989
[[0.36112344]]
[[0.04761905]]
[[0.40371521]]


### 연습문제 3.1.8

In [14]:
a = np.array([[1], [2]])
b = np.array([[2], [0]])

# b의 크기의 제곱 계산
b_norm_squared = np.dot(b.T, b)

# 투영성분 계산
a_parallel_b = (np.dot(a.T, b) / b_norm_squared) * b 

# 직교성분 계산
a_perpendicular_b = a - a_parallel_b

print(a_parallel_b)
print(a_perpendicular_b)

[[1.]
 [0.]]
[[0.]
 [2.]]


### 연습문제 3.1.9

In [16]:
# 단위벡터 v 정의 
v = np.array([[1], [0]])
v = v / np.linalg.norm(v)

# 임의의 점 x 정의
x = np.array([[3], [4]])

# x의 크기 제곱
x_norm_squared = np.dot(x.T, x)

# x를 v에 투영한 값
projection = np.dot(x.T, v)
print(projection)

# 거리 계산 (직교 성분의 크기)
distance = np.sqrt(x_norm_squared - projection**2)
print(distance)

# 거리 제곱 계산
distance_squared = x_norm_squared - projection**2
print(distance_squared)

[[3.]]
[[4.]]
[[16.]]
